version: "3.7"

services:
  api:
    build: ./example-todo-application-api
    depends_on:
      - db
    environment:
      DB_IP: db
      DB_USERNAME_FILE: /run/secrets/todo_app_db_username
      DB_PASSWORD_FILE: /run/secrets/todo_app_db_password
    secrets:
      - todo_app_db_username
      - todo_app_db_password
    networks:
      - app-front
      - app-back
    ports:
      - "8000:8000/tcp"

networks: 
  app-front:
  app-back: